In [1]:
import numpy as np
import pandas as pd

In [2]:
def input(n):
    if n == 1:
        a = np.array([0,1])
        return a
    elif n == 2:
        a = np.array([0,1,0,1])
        b = np.array([0,0,1,1])
        p = np.array([a,b])
        return p 
    else:
        return "Invalid Input Numbers"

In [3]:
def Mc_Culloch(n,k,T=0,w1=0,w2 = 0):
    Sum = 0
    I1 = 0
    I2 = 0
    I3 = 0
    arr = np.array([])
    if n == "NOT GATE":
        for x in k:
            Sum = Sum + (x*w1)
            if Sum >= T:
                arr = np.append(arr,1)
            elif Sum < T:
                arr = np.append(arr,0)
            sum = 0
        return arr
    elif n == "EXOR GATE":
        Tx = np.array([-1.5,0.5,1.5])
        Wx = np.array([1,1,1,-1,-1,1])
        for i in range(len(k)):
            a = k[i-1]
            b = k[i]
        for i in range(len(a)):
            I1 = I1 + (Wx[3]*a[i]) + (Wx[0]*b[i]) 
            I2 = I2 + (Wx[4]*a[i]) + (Wx[2]*b[i])
            if I1 >= Tx[1]:
                II1 = 1
            else:
                II1 = 0
            if I2 >= Tx[0]:
                II2 = 1
            else:
                II2 = 0
            I3 = I3 + (Wx[1]*I1) + (Wx[5] * I2)
            if I3 >= Tx[2]:
                arr = np.append(arr,1)
            elif I3 < Tx[2]:
                arr = np.append(arr,0)
            I3 = 0
            I2 = 0
            I1 = 0
        return arr
    else:
        for i in range(len(k)):
            a = k[i-1]
            b = k[i]
        for i in range(len(a)):
            Sum = Sum + (w1*b[i]) + (w2*a[i])
            if Sum >= T:
                arr = np.append(arr,1)
            elif Sum < T:
                arr = np.append(arr,0)
            sum = 0
        return arr
            
        
            
            
            
        
        

In [4]:
Mc_Culloch("NOT GATE",input(1),0,-1,-1)

array([1., 0.])

In [5]:
Mc_Culloch("AND GATE",input(2),3,1,1)

array([0., 0., 0., 1.])

In [6]:
Mc_Culloch("OR GATE",input(2),1,1,1)

array([0., 1., 1., 1.])

In [7]:
Mc_Culloch("NAND GATE",input(2),-2,-1,-1)

array([1., 1., 1., 0.])

In [8]:
Mc_Culloch("NOR GATE",input(2),0,1,1)

array([1., 1., 1., 1.])

In [9]:
Mc_Culloch("EXOR GATE",input(2),1)

array([0., 0., 1., 0.])